easy_admin:
  site_name : '<em style="font-size: 80%;">SymfonyBlog.</em>'
  design:
    brand_color: '#1ABC9C'
  entities:
    User :
      class: App\Entity\User
    Post :
      class : App\Entity\Post
    Comment:
      class: App\Entity\Comment